### PR TITLE
adding recursive method to retrieve all paths from a yaml file

### PR DESCRIPTION
**Pull request by qu1queee**
Hi,

Could we have a new invocation called `GetAllPaths()`, that will retrieve all paths in the YAML file. This will be helpful, some use cases I´m thinking are: 
 - comparing YAML files per path (differences, similarities)
 - deleting specific paths based on comparisons

I added a new test case for the function,its just checking if the number of all paths match the number of the array return by the function. Also, I saw that the `GetMapKeys() ` in the test cases,   it´s missing one map(`0: IntKey`)  is this intended?

Regards,
Enrique Encalada

### CODE REVIEW

**Comment by smallfish** [comment]
@qu1queee thanks for PR, but I feel a little problems:

- use `.` join the path, char `.` allowed for YAML key
- variable use Camel fmt

I think this commit part of helper/util, can create a new file :) `0: IntKey` is intended

**Comment by qu1queee** [comment]
@smallfish thanks for the feedback, I will work on this improvements this week, and made I commit again to the PR.

**Comment by qu1queee** [comment]
@smallfish I added a new commit to address the feedback you made. I required to modify the package name of your `simpleyaml_test.go` from `simpleyaml` to `simpleyaml_test`, otherwise with the new `util` package(using methods from `simpleyaml` package), we will have an import cycle, which Go doesn´t allow.

Regards,
Enrique Encalada

**Comment by smallfish** [comment]
@qu1queee thanks very much

**Pull request merged**
